### PR TITLE
Fixed stepper bug

### PR DESCRIPTION
**Pull request by joel-foo**
Resolved this issue: https://github.com/source-academy/js-slang/issues/1341

### CODE REVIEW

**Review by martin-henz — CHANGES_REQUESTED** [review]
The choice of variable name `stillEval` isn't right. It should be `limitExceeded`.

I was considering using the test
```
(reducedWithPath[0] as es.Program).body.length === 0)
```
in line 3002 and not introduce the boolean variable at all, but having the boolean variable `limitExceeded` makes things clearer.

**Comment by martin-henz** [comment]
Can you add a test case for this?

**Comment by joel-foo** [comment]
Sure, I will amend it accordingly.

**Review by martin-henz — APPROVED** [review]

**Comment by martin-henz** [comment]
fixes https://github.com/source-academy/js-slang/issues/1341

**Pull request merged**
