### PR TITLE
updated import and assignment syntax descriptions

### PR DESCRIPTION
**Pull request by martin-henz**
the title says it all

### CODE REVIEW

**Comment by openorclose** [comment]
I don't think this is correct, the original one looked good.

**Comment by martin-henz** [comment]
> I don't think this is correct, the original one looked good.

Can you be more specific. What is wrong?

**Comment by openorclose** [comment]
> > I don't think this is correct, the original one looked good.
> 
> Can you be more specific. What is wrong?

Oops I forgot to upload the screenshot, Let me update

**Comment by martin-henz** [comment]
> > > I don't think this is correct, the original one looked good.
> > 
> > 
> > Can you be more specific. What is wrong?
> 
> Oops I forgot to upload the screenshot, Let me update.
> 
> There shouldn't be any commas separating the import directives

OK fixed. Can you take another look?

**Review by openorclose — APPROVED** [review]
Looks good now!

**Pull request merged**
