### PR TITLE
Move list visualiser to chapter 2

### PR DESCRIPTION
**Pull request by remo5000**

### CODE REVIEW

**Comment by remo5000** [comment]
@ningyuansg Should we rename the function to `visualise_list`? I feel that `draw` is too similar to some external libraries

**Comment by ningyuansg** [comment]
@remo5000 try `draw_list`. Also, you need to rebase.

**Comment by ningyuansg** [comment]
@remo5000 Are you renaming this draw to draw_list or no?

**Comment by remo5000** [comment]
@ningyuansg Missed this out, done! I've updated the PR on the frontend as well

**Pull request merged**
