### PR TITLE
Added testing for pylib

### PR DESCRIPTION
**Pull request by JJtan2002**
Added test cases for pylib.
Added type safety by throwing errors for invalid argument types for binary operators in pylib.

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]

**Review by sayomaki — CHANGES_REQUESTED** [review]
Looks good! Do remember to fix the formatting of the code (by running `yarn format`) and we can proceed to merge this!

**Comment by sayomaki** [comment]
Another quick nitpick about the code changes, is there any reason why we are not using strict equality when checking the types?

**Comment by JJtan2002** [comment]
> Another quick nitpick about the code changes, is there any reason why we are not using strict equality when checking the types?

There isn't actually, we'll do a quick change. Thank you for all the help!

**Review by martin-henz — APPROVED** [review]
Looks good now.

**Pull request merged**
