### PR TITLE
fixing unicode errors in build: more fixes needed

### PR DESCRIPTION
**Pull request by martin-henz**

### CODE REVIEW

**Review by RichDom2185 — CHANGES_REQUESTED** [review]
We seem to be missing the leading backslashes of `\Theta` and `\Omega`.

Can we also add a check to the CI workflow?

**Comment by martin-henz** [comment]
> We seem to be missing the leading backslashes of `\Theta` and `\Omega`.
> 
> Can we also add a check to the CI workflow?



> We seem to be missing the leading backslashes of `\Theta` and `\Omega`.
> 
> Can we also add a check to the CI workflow?

The backslashes wouldn't lead to a good output. We could escape these things by saying ^$\Theta$^ to get a nice PDF.

But then the json output for autocomplete would look really ugly (unless we do some more magic). Also jsdoc would look bad.

So at the moment, docs/lib/list.js is used for:
* PDF
* jsdocs
* autocomplete
and we just tolerate a "Theta" appearing everywhere, to keep things simple.

**Comment by RichDom2185** [comment]
> We seem to be missing the leading backslashes of `\Theta` and `\Omega`.
> 
> Can we also add a check to the CI workflow?

Hi Prof @martin-henz, I've fixed these, though I can't check as I don't have LaTeX installed locally. Could you verify that it's correct now?

**Comment by RichDom2185** [comment]
> So at the moment, docs/lib/list.js is used for:
> 
> * PDF
> * jsdocs
> * autocomplete
> 
> and we just tolerate a "Theta" appearing everywhere, to keep things simple.

Replacing `Θ` with `&#1012` works nicely in JSDoc. How about the others?

**Comment by martin-henz** [comment]
> > So at the moment, docs/lib/list.js is used for:
> > 
> > * PDF
> > * jsdocs
> > * autocomplete
> > 
> > and we just tolerate a "Theta" appearing everywhere, to keep things simple.
> 
> Replacing `Θ` with `&#1012` works nicely in JSDoc. How about the others?

The file list.js is currently attached verbatim (using lstlisting in LaTeX) to source_2.pdf.

That means it will look ugly (illegible).

On the longer run, we should find a way to attach list.js in a nicer way to source_2.pdf.

I suggest we go ahead with just "Theta" (and make an issue) for now.

**Comment by RichDom2185** [comment]
> I suggest we go ahead with just "Theta" (and make an issue) for now.

Made the issue in #1705

**Review by RichDom2185 — APPROVED** [review]

**Pull request merged**
