### PR TITLE
SUBST

### PR DESCRIPTION
**Pull request by SwampertX**

### CODE REVIEW

**Comment by martin-henz** [comment]
Any instructions how I can use this branch? How can I play with it? What's the language currently supported?

**Comment by SwampertX** [comment]
> Any instructions how I can use this branch? How can I play with it? What's the language currently supported?

Still **not** a working prototype. The quickest way is to 
```bash
yarn build
node dist/repl/repl.js 1 subst
```
to run the REPL.

**Comment by SwampertX** [comment]
Last milestone left - make list prelude work.

**Comment by openorclose** [comment]
After much bug fixing, many edge cases have been taken care of. There's probably a few left, such as:
```function id(f) { return f; } id(id) === id(id);``` should be true, but returns false.

Nonetheless, it is a very useful tool, and these bugs can be sorted out along the way.

**Pull request merged**
