### PR TITLE
Add Source Compiler CI check

### PR DESCRIPTION
**Pull request by J0**
**Source -> Wasm Compiler**

This pull request adds a Github action to test if our Source->Wasm compiler can be integrated into Source-jslang.

### CODE REVIEW

**Comment by martin-henz** [comment]
Do I understand the logic right: When js-slang changes, this action would check if the Source -> Wasm Compiler breaks. If yes, we would not allow a push to the master branch of js-slang.

The problem that I see with this is that if Source -> Wasm Compiler is not maintained well, this might become a vulnerability for js-slang. Any views: @openorclose , @thomastanck

**Comment by martin-henz** [comment]
> Do I understand the logic right: When js-slang changes, this action would check if the Source -> Wasm Compiler breaks. If yes, we would not allow a push to the master branch of js-slang.
> 
> The problem that I see with this is that if Source -> Wasm Compiler is not maintained well, this might become a vulnerability for js-slang. Any views: @openorclose , @thomastanck

bump

Any views?

**Comment by J0** [comment]
> Do I understand the logic right: When js-slang changes, this action would check if the Source -> Wasm Compiler breaks. If yes, we would not allow a push to the master branch of js-slang.

When js-slang changes it will check if the Source->Wasm compiler in it's current state can be integrated with js-slang. If the integration of Source->wasm to the current repository fails then the push will be blocked.

We can leave this as a non-blocking check(Users can still merge if the build does not pass)

**Comment by J0** [comment]
Closed as per our telegram discussion

**Pull request closed without merging**
